name: Setup Self-Hosted Runner

on:
  workflow_run:
    workflows: ["Setup Self-Hosted Runner"]
    types:
      - requested

jobs:
  setup_runner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Self-Hosted Runner
      run: |
        mkdir actions-runner
        cd actions-runner
        curl -o actions-runner-linux-x64-2.312.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.312.0/actions-runner-linux-x64-2.312.0.tar.gz
        echo "85c1bbd104d539f666a89edef70a18db2596df374a1b51670f2af1578ecbe031  actions-runner-linux-x64-2.312.0.tar.gz" | shasum -a 256 -c
        tar xzf ./actions-runner-linux-x64-2.312.0.tar.gz
        ./config.sh --url https://github.com/nonoto999t/777 --token BE3XBEJZJZE4KRNT2QVKWADFWNTNM
